language: php

php:
  - '7.2'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache